version: 2
jobs:
  build:
    parallelism: 3
    docker:
    - image: circleci/ruby:2.3.7-stretch-node-browsers
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        PGHOST: 127.0.0.1
        PGUSER: root
        RAILS_ENV: test
        CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
        CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
        CYPRESS_VIDEOS_FOLDER: /tmp/circleci-test-artifacts/videos
        CYPRESS_SCREENSHOTS_FOLDER: /tmp/circleci-test-artifacts/screenshots

    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: pondo_test
        POSTGRES_PASSWORD: ""
    steps:
    - checkout
    - restore_cache:
        keys:
        - v5-rails-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - v5-rails-{{ .Branch }}-
        - v5-rails-
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - save_cache:
        key: v5-rails-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

    - restore_cache:
        keys:
        - v5-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v5-yarn-{{ .Branch }}-
        - v5-yarn-
    - run:
        name: Yarn Install
        command: yarn install --cache-folder ~/.cache/yarn
    - save_cache:
        key: v5-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn

    - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m

    - run:
        name: Database setup
        command: bundle exec rails db:schema:load --trace

    - run:
        name: Precompile assets
        # Asset on-the-fly compilation is currently slow
        # Precompile for faster test server response
        command: NODE_ENV=production bundle exec rails assets:precompile

    - run:
        name: Rails test server
        # We do this so that by the time cypress runs, the server is available
        command: 'PONDO_CYPRESS_RUN=yes bundle exec rails s -p 5002'
        background: true

    - run:
        name: RSpec
        command: bundle exec rspec --color --require spec_helper --format progress spec
        environment:
          RAILS_ENV: test
          RACK_ENV: test

    - run:
        name: Cypress
        command: yarn run cypressrun
        environment:
          RAILS_ENV: test
          RACK_ENV: test

    - run:
        name: Stop rails test server
        command: bundle exec ruby ./stop_test_server.rb

    - run:
        name: Prepare coverage results
        command: bundle exec ruby ./cresult.rb

    - run:
        name: Coveralls
        command: bundle exec rails coveralls:push

    - run:
        name: Coveralls webhook
        command: >
          curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
          -d "payload[build_num]=$CIRCLE_BUILD_NUM&payload[status]=done"

    - store_test_results:
        path: /tmp/circleci-test-results

    - store_artifacts:
        path: /tmp/circleci-artifacts
