version: 2
jobs:
  build:
    parallelism: 3
    docker:
    - image: circleci/ruby:2.3.7-stretch-node-browsers
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        PGHOST: 127.0.0.1
        PGUSER: root
        RAILS_ENV: test
        CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
        CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
        CYPRESS_VIDEOS_FOLDER: /tmp/circleci-test-results/videos
        CYPRESS_SCREENSHOTS_FOLDER: /tmp/circleci-test-results/screenshots

    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: pondo_test
        POSTGRES_PASSWORD: ""
    steps:
    - checkout
    - restore_cache:
        keys:
        - v5-rails-{{ checksum "Gemfile.lock" }}
        - v5-rails-
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - save_cache:
        key: v5-rails-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

    - restore_cache:
        keys:
        - v5-yarn-{{ checksum "yarn.lock" }}
        - v5-yarn-
    - run:
        name: Yarn Install
        command: yarn install --cache-folder ~/.cache/yarn
    - save_cache:
        key: v5-yarn-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn

    - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m

    - run:
        name: Preemptively start rails test server
        # We do this so that by the time cypress runs, the server is available
        command: yarn run rails_cypress_server

    - run:
        name: Database setup
        command: bundle exec rails db:schema:load --trace

    - run:
        name: RSpec
        command: bundle exec rspec --color --require spec_helper --format progress spec
        environment:
          RAILS_ENV: test
          RACK_ENV: test

    - run:
        name: Cypress
        command: yarn run cypressrun
        environment:
          RAILS_ENV: test
          RACK_ENV: test

    - run:
        name: Stop rails test server
        command: kill -9 $(cat tmp/pids/server.pid)

    - run: bundle exec rails coveralls:push
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts

