version: 2
jobs:
  build:
    parallelism: 3
    docker:
    - image: circleci/ruby:2.3.7-stretch-node-browsers
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        PGHOST: 127.0.0.1
        PGUSER: root
        RAILS_ENV: test
        CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
        CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: pondo_test
        POSTGRES_PASSWORD: ""
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS/cucumber
    - restore_cache:
        keys:
        - v5-rails-{{ checksum "Gemfile.lock" }}
        - v5-rails-
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - save_cache:
        key: v5-rails-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

    - restore_cache:
        keys:
        - v5-yarn-{{ checksum "yarn.lock" }}
        - v5-yarn-
    - run:
        name: Yarn Install
        command: yarn install --cache-folder ~/.cache/yarn
    - save_cache:
        key: v5-yarn-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn

    - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m

    - run:
        name: Database setup
        command: bundle exec rails db:schema:load --trace

    - run:
        command: bundle exec rspec --color --require spec_helper --format progress spec
        environment:
          RAILS_ENV: test
          RACK_ENV: test

    - run:
        command: 'bundle exec cucumber --format json --out $CIRCLE_TEST_REPORTS/cucumber/cucumber.cucumber '
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    - run: bundle exec rails coveralls:push
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: coverage
    - store_artifacts:
        path: /tmp/circleci-test-results

