version: 2
jobs:
  build:
    working_directory: ~/asartalo/pondo
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/ruby:2.3.7-stretch-node-browsers
    # - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    #  command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS/cucumber
    #- run:
    #    working_directory: ~/asartalo/pondo
    #    command: rm -f asartalo/pondo/.rvmrc; echo 2.3.4 > asartalo/pondo/.ruby-version; rvm use 2.3.4 --default
    - restore_cache:
        keys:
        - v4-rails-{{ checksum "Gemfile.lock" }}
        - v4-rails-
    #- run: ruby circle_ci_dependencies.rb
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - save_cache:
        key: v4-rails-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

    - restore_cache:
        keys:
        - v4-yarn-{{ checksum "yarn.lock" }}
        - v4-yarn-
    - run:
        name: Yarn Install
        command: yarn install --cache-folder ~/.cache/yarn
    - save_cache:
        key: v2-yarn-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn

    - run: |-
        mkdir -p config && echo 'test:
          database: circle_ruby_test
          adapter: postgresql
          encoding: unicode
          pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
          username: ubuntu
          host: localhost
        t >< jj' > config/database.yml
    - run:
        command: bundle exec rake db:create db:schema:load --trace
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    - run:
        command: bundle exec rspec --color --require spec_helper --format progress spec
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    - run:
        command: 'bundle exec cucumber --format json --out $CIRCLE_TEST_REPORTS/cucumber/cucumber.cucumber '
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    - run: bundle exec rails coveralls:push
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: coverage
    - store_artifacts:
        path: /tmp/circleci-test-results

