default: &default
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  google_key: <%= ENV["GOOGLE_KEY"] %>
  google_secret: <%= ENV["GOOGLE_SECRET"] %>

development:
  <<: *default
  secret_key_base: 918fdab735206fb9ac77f8029510ef38dd2e2f79871b069161f0414de3126247229aad74b2d4ee5f739e8fb569caf7227dd40c976af89e3cb2bdef7f0e824e64

test:
  <<: *default
  secret_key_base: ed43058e80313377202da953be773999c885db2eb36e8f7e0501b6a6a9ebffed3cc4bef3b443ef9152e4ab21a2b8fb7962eeecf890aebf9f402e2897a1ba8e3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

